### ISSUE TITLE
the caffe offset problem

### ISSUE THREAD

**Issue by RenieWell** [cjayanth95/liverseg#1]
I also run the code in https://github.com/IBBM/Cascaded-FCN, but I get the wrong prediction result as you got in the https://github.com/cjayanth95/liverseg/blob/master/custom_outs.ipynb. How do you fix this problem?
I am new to the caffe programing area, I would apriciate if you can tell me how to do.
Thank you!

**Comment by jayanth-culli** [comment]
I added offset parameters to step1_deploy.prototxt

**Comment by RenieWell** [comment]
I'll have a try, thank you!
